name: Evita CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - name: Install sudo package
      run: apt update && apt install sudo
    - name: Install SQLite3
      run: |
        apt-get install -y sqlite3 libsqlite3-dev
    - name: Install Readline
      run: apt install -y libreadline-dev
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec -s -t --error-trace
